import Head from 'next/head'
import NextLink from 'next/link'
import {
  Box,
  Button,
  Center,
  Container,
  Heading,
  HStack,
  Icon,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  Text,
  VStack,
} from '@chakra-ui/react'
import { ChevronDownIcon, UserCircleIcon } from '@heroicons/react/solid'
import { useAuthState } from 'lib/auth/state'
import { useSignOutAction } from 'lib/auth/sign-out/action'

interface LayoutProps {
  children: React.ReactNode
  isTitleHidden?: boolean
}
export function Layout({ children, isTitleHidden = false }: LayoutProps) {
  const authState = useAuthState()
  const { signOut } = useSignOutAction()
  return (
    <>
      <Head>
        <title>The first Next.js Testing conference(DEMO)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack minHeight="100vh">
        <HStack
          w="full"
          px={[2, 8]}
          mt={6}
          mb={12}
          minHeight={[18, 30]}
          justifyContent="space-between"
        >
          {isTitleHidden ? (
            <Box></Box>
          ) : (
            <NextLink href="/" passHref>
              <Heading fontSize={['lg', '3xl']} as="a" lineHeight={1}>
                <Text>The first Next.js Testing conference(DEMO)</Text>
              </Heading>
            </NextLink>
          )}
          {authState.authenticated && (
            <Box>
              <Menu placement="bottom-end">
                <MenuButton
                  as={Button}
                  rounded="full"
                  fontSize="sm"
                  rightIcon={<Icon as={ChevronDownIcon} />}
                >
                  <HStack>
                    <Icon as={UserCircleIcon} height={6} width={6} />
                    <HStack display={['none', 'flex']}>
                      <Text fontWeight="normal">Sign in </Text>
                      <Text>{authState.user.email}</Text>
                    </HStack>
                  </HStack>
                </MenuButton>
                <MenuList>
                  <MenuItem onClick={signOut}>Signout</MenuItem>
                </MenuList>
              </Menu>
            </Box>
          )}
        </HStack>
        <Container px={[2, 10]} maxW="container.lg" flex={1} paddingBottom={24}>
          {children}
        </Container>
        <Center color="gray.500" w="full" py={3}>
          <Text>Copyright © @toyamarinyon. All right reserved.</Text>
        </Center>
      </VStack>
    </>
  )
}
